/* API ENDPOINTS */
export const API_CREATE_ACCOUNT = 'auth/register';
export const API_LOGIN = 'auth/login';
export const API_CURRENT_ACCOUNT = 'auth/me';

/* AUTH */
export const USER_TOKEN_KEY = 'USER_TOKEN_KEY';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const AUTHORIZE_LOGIN = 'AUTHORIZE_LOGIN';
export const AUTHORIZE_LOGIN_SUCCESS = 'AUTHORIZE_LOGIN_SUCCESS';
export const AUTHORIZE_LOGIN_ERROR = 'AUTHORIZE_LOGIN_ERROR';

export const REFRESH_USER_INFO = 'REFRESH_USER_INFO';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';